### ISSUE TITLE
The ownership diagram of [view_examples] is not showing up when view_examples.sh gets started.

### ISSUE THREAD

**Issue by Erik1288** [fplab/rustviz#32]
![image](https://user-images.githubusercontent.com/8181966/132353775-16ec9acf-5841-49b4-879f-49271a945f2a.png)
![image](https://user-images.githubusercontent.com/8181966/132354025-2149eeb7-337d-4c98-a958-2fa5b26ee8e7.png)

./view_examples.sh
Generating visualizations for the following examples:
building extra_credit...done
2021-09-07 21:28:18 [INFO] (mdbook::book): Book building has started
2021-09-07 21:28:18 [INFO] (mdbook::book): Running the html backend
Serving HTTP on :: port 8000 (http://[::]:8000/) ...

rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)

rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)

cargo --version
cargo 1.54.0 (5ae8d74b3 2021-06-22)

mdbook --version
mdbook v0.4.12

**Comment by Serenali-1108** [comment]
Issue fixed by setting svg file display from none to flex in view_examples.sh, ownership diagram should now be showing when running view_examples.sh
