### ISSUE TITLE
Http server and Python

### ISSUE THREAD

**Issue by kevinmcfarlane** [fplab/rustviz#42]
In [view_examples.sh](https://github.com/rustviz/rustviz/blob/master/rustviz_mdbook/view_examples.sh) I had to replace

`python3 -m http.server 8000`

with

`python -m http.server 8000`

This was on Windows. I did actually have Python 3.x installed but second command works.

You probably should mention this has a dependency on Python too. Is Python typically pre-installed in Linux distros? I gather it is in macOS.

**Comment by Serenali-1108** [comment]
we had removed using Python to display mdbook on localhost, now the book doesn't depend on Python.
